name: Tag on PR Approval

on:
  pull_request:
    types: [closed]
permissions:
  contents: write

jobs:
  on_merge:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Check if PR is merged
      run: |
        # Get the list of reviews for the PR
        echo "GITHUB_TOKEN is set to: $GITHUB_TOKEN"  # This won't display the token itself, but helps confirm availability
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        mergedBy=$(gh pr view ${{ github.event.pull_request.number }} --json mergedBy)
        if [[ -n "$mergedBy" ]]; then
          echo "PR is approved, creating a tag."
          # Create a tag with the current date or commit hash as tag name
          tag_name="$REPO_NAME-$(date +'%Y-%m-%d-%H-%M-%S')"  # You can change this to any naming format you prefer
          git tag $tag_name
          git push origin $tag_name
        else
          echo "PR is not approved yet, no tag created."
        fi

    - name: Push tag
      run: |
        git push --tags
      if: success()  # Push the tag only if the PR is approved
